system-default-registry: "MYREGISTRY"
cluster-cidr: "MYRANGEIP01/16"
service-cidr: "MYRANGEIP02/16"
cni: "calico"
disable: "rke2-ingress-nginx"
write-kubeconfig-mode: "0644"
tls-san:
  - "AMODIFIER_TLSSAN"
kubelet-arg:
  - "eviction-hard=imagefs.available<15%,memory.available<100Mi,nodefs.available<10%,nodefs.inodesFree<5%"
  - "eviction-pressure-transition-period=5m0s"
  - "image-gc-high-threshold=65"
  - "image-gc-low-threshold=50"
  - "oom-score-adj=-999"
  - "v=8"
# node-taint:
#   - "node-role.kubernetes.io/control-plane:NoSchedule"
#   - "node-role.kubernetes.io/etcd:NoExecute"
cloud-provider-name: "rancher-vsphere"
cloud-provider-config: "/etc/rancher/rke2/vsphere.conf"
debug: true
